// This file was auto-generated by x10. Do not modify by hand.
// @flow

import * as React from 'react';
import { createFragmentContainer, graphql } from 'react-relay';

import Group from 'latitude/Group';
import HelpTooltip from 'latitude/HelpTooltip';

import TextDisplay from 'react_lib/display/TextDisplay';
import Button from 'react_lib/latitude_wrappers/Button';
import VerticalStackPanel from 'react_lib/layout/VerticalStackPanel';
import StyleControl from 'react_lib/StyleControl';

import { type Address } from 'client_page/entities/Address';

import { type AddressDisplay_address } from './__generated__/AddressDisplay_address.graphql';



type Props = {|
  +address: AddressDisplay_address,
|};
function AddressDisplay(props: Props): React.Node {
  const { address } = props;

  return (
    <VerticalStackPanel
      gap={ 0 }
    >
      <TextDisplay
        value={ address?.theAddress }
      />
      <TextDisplay
        value={ address?.theAddress2 }
      />
      <StyleControl
        maxWidth={ 400 }
      >
        <TextDisplay
          value={ address?.city }
        />
      </StyleControl>
      <StyleControl
        maxWidth={ 150 }
      >
        <TextDisplay
          value={ address?.postalCode }
        />
      </StyleControl>
      <TextDisplay
        value={ address?.country?.name }
      />
      <VerticalStackPanel>
        <Button
          label='Verify'
        />
        <Group
          alignItems='center'
        >
          <Button
            label='Make Location'
          />
          <HelpTooltip
            text='Create a location with this address...'
          />
        </Group>
      </VerticalStackPanel>
    </VerticalStackPanel>
  );
}

// $FlowExpectedError
export default createFragmentContainer(AddressDisplay, {
  address: graphql`
    fragment AddressDisplay_address on Address {
      id
      city
      country {
        id
        toStringRepresentation
        name
      }
      postalCode
      theAddress
      theAddress2
    }
  `,
});

