name: Base
description: Provides attribute(s) common to all entities
abstract: true

attributes:
  - name: id
    dataType: String
    description: The unique id associated posessed by all entries. Used by GQL.
    mandatory: true
    readOnly: true
    idAttribute: true
