// Auto-generated by x10 - do not edit
using System;
using System.Collections.Generic;

using HotChocolate;

using x10.hotchoc.SmallSample.Repositories;

namespace x10.hotchoc.SmallSample.Entities {
  /// <summary>
  /// A physical or mailing address
  /// </summary>
  public class Address : Base {
    // Regular Attributes
    public string? UnitNumber { get; set; }
    public string? TheAddress { get; set; }
    public string? City { get; set; }
    public string? StateOrProvince { get; set; }
    public string? Zip { get; set; }

    // Associations
    public Country? Country { get; set; }

    public override void EnsureUniqueDbid() {
      base.EnsureUniqueDbid();
    }

    internal override void SetNonOwnedAssociations(IRepository repository) {
      base.SetNonOwnedAssociations(repository);

      int? country = IdUtils.FromFrontEndId(Country?.Id);
      Country = country == null ? null : repository.GetCountry(country.Value);
    }
  }
}

