// This file was auto-generated by x10. Do not modify by hand.
// @flow


import { v4 as uuid } from 'uuid';

import { addError, type FormError } from 'react_lib/form/FormProvider';
import isBlank from 'react_lib/utils/isBlank';


// Type Definition
export type Client = {
  +id: string,
  +dbid: ?number,
  +name: string,
};


// Create Default Function
export function createDefaultClient(): Client {
  return {
    id: uuid(),
    dbid: null,
    name: '',
  };
}


// Validations
export function clientCalculateErrors(client: Client, prefix?: string, inListIndex?: number): $ReadOnlyArray<FormError> {
  const errors = [];
  if (client == null ) return errors;

  if (isBlank(client.name))
    addError(errors, prefix, 'Name is required', ['name'], inListIndex);

  return errors;
}

