// This file was auto-generated by x10. Do not modify by hand.
// @flow


import { v4 as uuid } from 'uuid';

import { addError, type FormError } from 'react_lib/form/FormProvider';
import isBlank from 'react_lib/utils/isBlank';
import toEnum from 'react_lib/utils/toEnum';

import { type Attachment } from 'dps/entities/Attachment';
import { type CompanyEntity } from 'dps/entities/CompanyEntity';
import { type MatchInfo } from 'dps/entities/MatchInfo';
import { type Message } from 'dps/entities/Message';
import { type OldHit } from 'dps/entities/OldHit';
import { type Shipment } from 'dps/entities/Shipment';
import { type User } from 'dps/entities/User';
import { type WhitelistDuration } from 'dps/entities/WhitelistDuration';
import { type HitStatusEnum, type ReasonForCleranceEnum } from 'dps/sharedEnums';


// Type Definition
export type Hit = {
  +id: string,
  +priority: ?PriorityEnum,
  +status: ?HitStatusEnum,
  +reasonForClearance: ?ReasonForCleranceEnum,
  +notes: string,
  +companyEntity: ?CompanyEntity,
  +user: ?User,
  +attachments: $ReadOnlyArray<Attachment>,
  +matches: $ReadOnlyArray<MatchInfo>,
  +shipments: $ReadOnlyArray<Shipment>,
  +messages: $ReadOnlyArray<Message>,
  +oldHits: $ReadOnlyArray<OldHit>,
  +whitelistDays: ?WhitelistDuration,
};


// Enums
export const PriorityEnumPairs = [
  {
    value: 'low',
    label: 'Low',
  },
  {
    value: 'middle',
    label: 'Middle',
  },
  {
    value: 'high',
    label: 'High',
  },
];

export type PriorityEnum = 'low' | 'middle' | 'high';



// Create Default Function
export function createDefaultHit(): Hit {
  return {
    id: uuid(),
    priority: null,
    status: 'unresolved',
    // $FlowExpectedError Required field, but no default value
    reasonForClearance: null,
    notes: '',
    companyEntity: null,
    user: null,
    attachments: [],
    matches: [],
    shipments: [],
    messages: [],
    oldHits: [],
    whitelistDays: null,
  };
}


// Validations
export function hitCalculateErrors(hit: Hit, prefix?: string): $ReadOnlyArray<FormError> {
  const errors = [];
  if (hit == null ) return errors;

  if (isBlank(hit.reasonForClearance))
    addError(errors, prefix, 'Reason For Clearance is required', ['reasonForClearance']);
  if (isBlank(hit.notes))
    addError(errors, prefix, 'Notes is required', ['notes']);
  if (isBlank(hit.whitelistDays))
    addError(errors, prefix, 'Whitelist Days is required', ['whitelistDays']);

  if (toEnum(hit?.status) == "unresolved")
    addError(errors, prefix, 'Please select one of the choices above', ['status']);

  return errors;
}

