// This file was auto-generated by x10. Do not modify by hand.
// @flow


import { v4 as uuid } from 'uuid';

import { addError, type FormError } from 'react_lib/form/FormProvider';
import isBlank from 'react_lib/utils/isBlank';

import { type User } from 'dps/entities/User';


// Type Definition
export type HitEdit = {
  +id: string,
  +editedFields: string,
  +timestamp: ?string,
  +user: ?User,
};


// Create Default Function
export function createDefaultHitEdit(): HitEdit {
  return {
    id: uuid(),
    editedFields: '',
    // $FlowExpectedError Required field, but no default value
    timestamp: null,
    user: null,
  };
}


// Validations
export function hitEditCalculateErrors(hitEdit: HitEdit, prefix?: string): $ReadOnlyArray<FormError> {
  const errors = [];
  if (hitEdit == null ) return errors;

  if (isBlank(hitEdit.editedFields))
    addError(errors, prefix, 'Edited Fields is required', ['editedFields']);
  if (isBlank(hitEdit.timestamp))
    addError(errors, prefix, 'Timestamp is required', ['timestamp']);
  if (isBlank(hitEdit.user))
    addError(errors, prefix, 'User is required', ['user']);

  return errors;
}

