// This file was auto-generated by x10. Do not modify by hand.
// @flow


import { v4 as uuid } from 'uuid';

import { addError, type FormError } from 'react_lib/form/FormProvider';
import isBlank from 'react_lib/utils/isBlank';
import x10toString from 'react_lib/utils/x10toString';

import { type Attachment } from 'dps/entities/Attachment';


// Type Definition
export type Message = {
  +id: string,
  +timestamp: ?string,
  +text: string,
  +coreShipmentId: ?number,
  +user: ?{ id: string },
  +attachments: $ReadOnlyArray<Attachment>,
};


// Derived Attribute Functions
export function messageFlexId(message: {
  +coreShipmentId: ?number,
}): string {
  const result = 'Flex-' + x10toString(message?.coreShipmentId);
  return result;
}



// Create Default Function
export function createDefaultMessage(): Message {
  return {
    id: uuid(),
    timestamp: null,
    text: '',
    coreShipmentId: null,
    user: null,
    attachments: [],
  };
}


// Validations
export function messageCalculateErrors(message: Message, prefix?: string): $ReadOnlyArray<FormError> {
  const errors = [];
  if (message == null ) return errors;

  if (isBlank(message.user))
    addError(errors, prefix, 'User is required', ['user']);

  return errors;
}

