// This file was auto-generated by x10. Do not modify by hand.
// @flow


import { v4 as uuid } from 'uuid';

import { addError, type FormError } from 'react_lib/form/FormProvider';
import isBlank from 'react_lib/utils/isBlank';


// Type Definition
export type SuggestedResource = {
  +id: string,
  +type: ?SuggestedResourceTypeEnum,
  +title: string,
  +text: string,
  +helpful: boolean,
};


// Enums
export const SuggestedResourceTypeEnumPairs = [
  {
    value: 'GOOGLE',
    label: 'Google',
  },
  {
    value: 'LINKED_IN',
    label: 'Linked In',
  },
];

export type SuggestedResourceTypeEnum = 'GOOGLE' | 'LINKED_IN';



// Create Default Function
export function createDefaultSuggestedResource(): SuggestedResource {
  return {
    id: uuid(),
    type: null,
    title: '',
    text: '',
    helpful: false,
  };
}


// Validations
export function suggestedResourceCalculateErrors(suggestedResource: SuggestedResource, prefix?: string): $ReadOnlyArray<FormError> {
  const errors = [];
  if (suggestedResource == null ) return errors;


  return errors;
}

