// This file was auto-generated by x10. Do not modify by hand.
// @flow


import { v4 as uuid } from 'uuid';

import { addError, type FormError } from 'react_lib/form/FormProvider';
import isBlank from 'react_lib/utils/isBlank';


// Type Definition
export type User = {
  +id: string,
  +firstName: string,
  +lastName: string,
  +email: string,
};


// Create Default Function
export function createDefaultUser(): User {
  return {
    id: uuid(),
    firstName: '',
    lastName: '',
    email: '',
  };
}


// Validations
export function userCalculateErrors(user: User, prefix?: string): $ReadOnlyArray<FormError> {
  const errors = [];
  if (user == null ) return errors;


  return errors;
}

