// This file was auto-generated by x10. Do not modify by hand.
// @flow


import { v4 as uuid } from 'uuid';

import { addError, type FormError } from 'react_lib/form/FormProvider';
import isBlank from 'react_lib/utils/isBlank';


// Type Definition
export type WhitelistDuration = {
  +id: string,
  +value: ?number,
  +label: string,
};


// Create Default Function
export function createDefaultWhitelistDuration(): WhitelistDuration {
  return {
    id: uuid(),
    value: null,
    label: '',
  };
}


// Validations
export function whitelistDurationCalculateErrors(whitelistDuration: WhitelistDuration, prefix?: string): $ReadOnlyArray<FormError> {
  const errors = [];
  if (whitelistDuration == null ) return errors;


  return errors;
}

