// This file was auto-generated by x10. Do not modify by hand.
// @flow

import { v4 as uuid } from 'uuid';

import { DBID_LOCALLY_CREATED } from 'react_lib/constants';


// Type Definition
export type __Context__ = {|
  +today: Date,
|};


