// This file was auto-generated by x10. Do not modify by hand.
// @flow

import { v4 as uuid } from 'uuid';

import { DBID_LOCALLY_CREATED } from 'react_lib/constants';


// Type Definition
export type Address = {|
  +id: string,
  +dbid: number,
  +unitNumber: string,
  +theAddress: string,
  +city: string,
  +stateOrProvince: string,
  +zip: string,
|};


// Create Default Function
export function createDefaultAddress(): Address {
  return {
    id: uuid(),
    dbid: DBID_LOCALLY_CREATED,
    unitNumber: '',
    theAddress: '',
    city: '',
    stateOrProvince: '',
    zip: '',
  };
}


// Derived Attribute Functions
export function addressFirstAddressLine(address: Address): string {
  const result = address.theAddress + '   Unit ' + address.unitNumber;
  return result;
}
export function addressSecondAddressLine(address: Address): string {
  const result = address.city + ', ' + address.stateOrProvince;
  return result;
}
export function addressThirdAddressLine(address: Address): string {
  const result = address.zip;
  return result;
}


