// This file was auto-generated by x10. Do not modify by hand.
// @flow


import { createDefaultTenant, type Tenant } from 'entities/Tenant';
import { createDefaultUnit, type Unit } from 'entities/Unit';
import { addError, type FormError } from 'react_lib/form/FormProvider';
import isBlank from 'react_lib/utils/isBlank';
import { v4 as uuid } from 'uuid';

// Type Definition
export type Move = {|
  +id: string,
  +date: ?string,
  +from: Unit,
  +to: Unit,
  +tenant: Tenant,
|};


// Create Default Function
export function createDefaultMove(): Move {
  return {
    id: uuid(),
    // $FlowExpectedError Required field, but no default value
    date: null,
    from: createDefaultUnit(),
    to: createDefaultUnit(),
    tenant: createDefaultTenant(),
  };
}


// Validations
export function moveCalculateErrors(move: Move, prefix?: string): $ReadOnlyArray<FormError> {
  const errors = [];

  if (isBlank(move.date))
    addError(errors, prefix, 'Date is required', ['date']);

  return errors;
}

