// This file was auto-generated by x10. Do not modify by hand.
// @flow

import * as React from 'react';
import { Route } from 'react-router-dom';

import VerticalStackPanel from 'react_lib/layout/VerticalStackPanel';
import Menu from 'react_lib/menu/Menu';
import MenuItem from 'react_lib/menu/MenuItem';
import SpaContent from 'react_lib/SpaContent';

import HitsInterface from 'dps/ui/HitsInterface';
import SlideoutPanelInterface from 'dps/ui/SlideoutPanelInterface';
import WorkspaceTabsInterface from 'dps/ui/WorkspaceTabsInterface';



type Props = {|
|};
export default function Header(props: Props): React.Node {
  const {  } = props;

  return (
    <VerticalStackPanel>
      <Menu>
        <MenuItem
          label='Hits'
          href='/hits'
        />
      </Menu>
      <SpaContent
        rootComponent={ HitsInterface }
      >
        <Route exact path='/hits/panel/:id' component={ SlideoutPanelInterface } />
        <Route exact path='/hits' component={ HitsInterface } />
        <Route exact path='/hits/:id' component={ WorkspaceTabsInterface } />
      </SpaContent>
    </VerticalStackPanel>
  );
}

