// This file was auto-generated by x10. Do not modify by hand.
// @flow

import * as React from 'react';
import { createFragmentContainer, graphql } from 'react-relay';

import Group from 'latitude/Group';
import Text from 'latitude/Text';

import EnumDisplay from 'react_lib/display/EnumDisplay';
import TextDisplay from 'react_lib/display/TextDisplay';
import Button from 'react_lib/latitude_wrappers/Button';
import Table from 'react_lib/table/Table';

import { PriorityEnumPairs, type Hit } from 'dps/entities/Hit';

import { type Hits_hits } from './__generated__/Hits_hits.graphql';



type Props = {|
  +hits: Hits_hits,
|};
function Hits(props: Props): React.Node {
  const { hits } = props;

  return (
    <Group
      flexDirection='column'
    >
      <Text
        scale='display'
        children='Hits'
      />
      <Table
        data={ hits }
        columns={
          [
            {
              id: 'Name',
              Header: 'Name',
              width: 140,
              accessor: (data) => data?.companyEntity?.name,
              Cell: ({ value }) =>
                <TextDisplay
                  value={ value }
                />
              ,
            },
            {
              id: 'Priority',
              Header: 'Priority',
              width: 140,
              accessor: (data) => data?.priority,
              Cell: ({ value }) =>
                <EnumDisplay
                  value={ value }
                  options={ PriorityEnumPairs }
                />
              ,
            },
            {
              id: 'Go-To',
              Header: 'Go-To',
              width: 140,
              accessor: (data) => data,
              Cell: ({ value }) =>
                <Group>
                  <Button
                    label='Go-To'
                    url={ '/hits/' + value?.id }
                  />
                </Group>
              ,
            },
          ]
        }
      />
    </Group>
  );
}

// $FlowExpectedError
export default createFragmentContainer(Hits, {
  hits: graphql`
    fragment Hits_hits on Hit @relay(plural: true) {
      id
      companyEntity {
        id
        toStringRepresentation
        name
      }
      priority
    }
  `,
});

