// This file was auto-generated by x10. Do not modify by hand.
// @flow

import * as React from 'react';
import { createFragmentContainer, graphql } from 'react-relay';

import Text from 'latitude/Text';

import { type Shipment } from 'dps/entities/Shipment';

import { type ShipmentTab_shipments } from './__generated__/ShipmentTab_shipments.graphql';



type Props = {|
  +shipments: ShipmentTab_shipments,
|};
function ShipmentTab(props: Props): React.Node {
  const { shipments } = props;

  return (
    <Text
      scale='display'
      children='TBD Shipments'
    />
  );
}

// $FlowExpectedError
export default createFragmentContainer(ShipmentTab, {
  shipments: graphql`
    fragment ShipmentTab_shipments on Shipment @relay(plural: true) {
      id
    }
  `,
});

