// This file was auto-generated by x10. Do not modify by hand.
// @flow

import * as React from 'react';
import { createFragmentContainer, graphql } from 'react-relay';

import  from 'latitude/';
import Text from 'latitude/Text';

import { type Hit } from 'dps/entities/Hit';

import { type WorkspaceTabs_hit } from './__generated__/WorkspaceTabs_hit.graphql';



type Props = {|
  +hit: WorkspaceTabs_hit,
|};
function WorkspaceTabs(props: Props): React.Node {
  const { hit } = props;

  return (
    <
      displayFunc: () =>
        <Text
          scale='display'
          children='TODO'
        />
      ,
    >
      <Text
        scale='display'
        children='TODO'
      />
    </>
  );
}

// $FlowExpectedError
export default createFragmentContainer(WorkspaceTabs, {
  hit: graphql`
    fragment WorkspaceTabs_hit on Hit {
      id
    }
  `,
});

