// This file was auto-generated by x10. Do not modify by hand.
// @flow

import environment from 'environment';
import * as React from 'react';
import MultiEntityQueryRenderer from 'react_lib/relay/MultiEntityQueryRenderer';
import { graphql, QueryRenderer } from 'react-relay';
import Buildings from 'ui/Buildings';


export default function BuildingsInterface(props: { }): React.Node { 
  return (
    <MultiEntityQueryRenderer
      createComponentFunc={ (buildings) => <Buildings buildings={ buildings }/> }
      query={ query }
    />
  );
}

const query = graphql`
  query BuildingsInterfaceQuery {
    entities: buildings {
      nodes {
        ...Buildings_buildings
      }
    }
  }
`;

