// This file was auto-generated by x10. Do not modify by hand.
// @flow

import { createDefaultMove } from 'entities/Move';
import environment from 'environment';
import * as React from 'react';
import EntityQueryRenderer from 'react_lib/relay/EntityQueryRenderer';
import { graphql, QueryRenderer } from 'react-relay';
import MoveView, { MoveViewStateful } from 'ui/MoveView';


type Props = { 
  +match: { 
    +params: { 
      +id: string
    }
  }
};
export default function MoveViewInterface(props: Props): React.Node {
  return (
    <EntityQueryRenderer
      match={ props.match }
      createComponentFunc={ (move) => <MoveView move={ move }/> }
      createComponentFuncNew={ () => <MoveViewStateful move={ createDefaultMove() }/> }
      query={ query }
    />
  );
}

const query = graphql`
  query MoveViewInterfaceQuery($id: String!) {
    entity: move(id: $id) {
      ...MoveView_move
    }
  }
`;

