// This file was auto-generated by x10. Do not modify by hand.
// @flow

import environment from 'environment';
import * as React from 'react';
import { graphql, QueryRenderer } from 'react-relay';
import MoveView from 'ui/MoveView';


