// This file was auto-generated by x10. Do not modify by hand.
// @flow

import { type MoveView_move } from './__generated__/MoveView_move.graphql';
import { type Move } from 'entities/Move';
import Text from 'latitude/Text';
import TextInput from 'latitude/TextInput';
import * as React from 'react';
import DisplayField from 'react_lib/form/DisplayField';
import DisplayForm from 'react_lib/form/DisplayForm';
import FormSection from 'react_lib/form/FormSection';
import Separator from 'react_lib/Separator';
import { createFragmentContainer, graphql } from 'react-relay';
import BuildingView from 'ui/BuildingView';


type Props = {|
  +move: MoveView_move,
|};
function MoveView(props: Props): React.Node {
  const { move } = props;

  return (
    <DisplayForm>
      <Text
        scale='display'
        children='Move Details'
      />
      <Separator/>
      <FormSection
        label='Moving from location...'
      >
        <BuildingView/>
      </FormSection>
      <FormSection
        label='Moving to location...'
      >
        <BuildingView/>
      </FormSection>
      <FormSection
        label='Tenant details...'
      >
        <DisplayField
          label='Name'
        >
          <TextInput
            value={ move.tenant.name }
            onChange={ (value) => {
              let newObj = JSON.parse(JSON.stringify(move));
              newObj.tenant.name = value;
              onChange(newObj);
            } }
          />
        </DisplayField>
        <DisplayField
          label='Phone'
        >
          <TextInput
            value={ move.tenant.phone }
            onChange={ (value) => {
              let newObj = JSON.parse(JSON.stringify(move));
              newObj.tenant.phone = value;
              onChange(newObj);
            } }
          />
        </DisplayField>
        <DisplayField
          label='Email'
        >
          <TextInput
            value={ move.tenant.email }
            onChange={ (value) => {
              let newObj = JSON.parse(JSON.stringify(move));
              newObj.tenant.email = value;
              onChange(newObj);
            } }
          />
        </DisplayField>
        <DisplayField
          label='The Address'
        >
          <TextInput
            value={ move.tenant.permanentMailingAddress.theAddress }
            onChange={ (value) => {
              let newObj = JSON.parse(JSON.stringify(move));
              newObj.tenant.permanentMailingAddress.theAddress = value;
              onChange(newObj);
            } }
          />
        </DisplayField>
      </FormSection>
    </DisplayForm>
  );
}

// $FlowExpectedError
export default createFragmentContainer(MoveView, {
  move: graphql`
    fragment MoveView_move on Move {
      id
      from {
        id
      }
      tenant {
        id
        email
        name
        permanentMailingAddress {
          id
          theAddress
        }
        phone
      }
      to {
        id
      }
    }
  `,
});

