// This file was auto-generated by x10. Do not modify by hand.
// @flow

import * as React from 'react';

import Group from 'latitude/Group';
import Text from 'latitude/Text';
import TextInput from 'latitude/TextInput';
import FormField from 'react_lib/form/FormField';
import FormProvider from 'react_lib/form/FormProvider';
import FormSection from 'react_lib/form/FormSection';
import FormSubmitButton from 'react_lib/form/FormSubmitButton';
import basicCommitMutation from 'react_lib/relay/basicCommitMutation';
import Separator from 'react_lib/Separator';
import { graphql } from 'react-relay';


import { type Tenant } from 'entities/Tenant';

type Props = {|
  +tenant: Tenant,
  +onChange: (tenant: Tenant) => void,
|};
export default function TenantForm(props: Props): React.Node {
  const { tenant, onChange } = props;

  return (
    <FormProvider
      value={ [] }
    >
      <Text
        scale='display'
        children='New Tenant'
      />
      <Separator/>
      <FormSection
        label='Tenant Info'
      >
        <FormField
          label='Name'
        >
          <TextInput
            value={ tenant.name }
            onChange={ (value) => {
              onChange({ ...tenant, name: value })
            } }
          />
        </FormField>
        <FormField
          label='Phone'
        >
          <TextInput
            value={ tenant.phone }
            onChange={ (value) => {
              onChange({ ...tenant, phone: value })
            } }
          />
        </FormField>
        <FormField
          label='Email'
        >
          <TextInput
            value={ tenant.email }
            onChange={ (value) => {
              onChange({ ...tenant, email: value })
            } }
          />
        </FormField>
      </FormSection>
      <FormSection
        label='Permanent Mailing Address'
      >
        <FormField
          label='The Address'
        >
          <TextInput
            value={ tenant.permanentMailingAddress.theAddress }
            onChange={ (value) => {
              let newObj = JSON.parse(JSON.stringify(tenant));
              newObj.permanentMailingAddress.theAddress = value;
              onChange(newObj);
            } }
          />
        </FormField>
        <FormField
          label='City'
          maxWidth={ 400 }
        >
          <TextInput
            value={ tenant.permanentMailingAddress.city }
            onChange={ (value) => {
              let newObj = JSON.parse(JSON.stringify(tenant));
              newObj.permanentMailingAddress.city = value;
              onChange(newObj);
            } }
          />
        </FormField>
        <FormField
          label='State Or Province'
          maxWidth={ 250 }
        >
          <TextInput
            value={ tenant.permanentMailingAddress.stateOrProvince }
            onChange={ (value) => {
              let newObj = JSON.parse(JSON.stringify(tenant));
              newObj.permanentMailingAddress.stateOrProvince = value;
              onChange(newObj);
            } }
          />
        </FormField>
        <FormField
          label='Zip or Postal Code'
          maxWidth={ 150 }
        >
          <TextInput
            value={ tenant.permanentMailingAddress.zip }
            onChange={ (value) => {
              let newObj = JSON.parse(JSON.stringify(tenant));
              newObj.permanentMailingAddress.zip = value;
              onChange(newObj);
            } }
          />
        </FormField>
      </FormSection>
      <Group
        justifyContent='space-between'
      >
        <Text
          children='* Required'
        />
        <FormSubmitButton
          onClick={ () => save(tenant) }
        />
      </Group>
    </FormProvider>
  );
}

function save(tenant: Tenant) {
  const variables = {
    dbid: tenant.dbid,
    name: tenant.name,
    phone: tenant.phone,
    email: tenant.email,
    permanentMailingAddress: tenant.permanentMailingAddress,
  };

  basicCommitMutation(mutation, variables);
}

const mutation = graphql`
  mutation TenantFormMutation(
    $dbid: Int!
    $name: String!
    $phone: String!
    $email: String!
    $permanentMailingAddress: AddressInput!
  ) {
    createOrUpdateTenant(
      dbid: $dbid
      name: $name
      phone: $phone
      email: $email
      permanentMailingAddress: $permanentMailingAddress
    )
  }
`;

