// This file was auto-generated by x10. Do not modify by hand.
// @flow


import { v4 as uuid } from 'uuid';

import { addError, type FormError } from 'react_lib/form/FormProvider';
import isBlank from 'react_lib/utils/isBlank';


// Type Definition
export type Address = {
  +id: string,
  +theAddress: string,
  +theAddress2: string,
  +city: string,
  +postalCode: string,
  +verified: boolean,
  +country: ?{ id: string },
  +stateOrProvince: ?{ id: string },
};


// Create Default Function
export function createDefaultAddress(): Address {
  return {
    id: uuid(),
    theAddress: '',
    theAddress2: '',
    city: '',
    postalCode: '',
    verified: false,
    country: null,
    stateOrProvince: null,
  };
}


// Validations
export function addressCalculateErrors(address: Address, prefix?: string): $ReadOnlyArray<FormError> {
  const errors = [];

  if (isBlank(address.theAddress))
    addError(errors, prefix, 'The Address is required', ['theAddress']);
  if (isBlank(address.city))
    addError(errors, prefix, 'City is required', ['city']);
  if (isBlank(address.country))
    addError(errors, prefix, 'Country is required', ['country']);
  if (isBlank(address.stateOrProvince))
    addError(errors, prefix, 'State Or Province is required', ['stateOrProvince']);

  return errors;
}

