// This file was auto-generated by x10. Do not modify by hand.
// @flow


import { v4 as uuid } from 'uuid';

import { addError, type FormError } from 'react_lib/form/FormProvider';
import isBlank from 'react_lib/utils/isBlank';


// Type Definition
export type CompanyEntityCountryService = {
  +id: string,
  +importCustoms: boolean,
  +exportCustoms: boolean,
  +country: ?string,
};


// Create Default Function
export function createDefaultCompanyEntityCountryService(): CompanyEntityCountryService {
  return {
    id: uuid(),
    importCustoms: false,
    exportCustoms: false,
    country: null,
  };
}


// Validations
export function companyEntityCountryServiceCalculateErrors(companyEntityCountryService: CompanyEntityCountryService, prefix?: string): $ReadOnlyArray<FormError> {
  const errors = [];

  if (isBlank(companyEntityCountryService.country))
    addError(errors, prefix, 'Country is required', ['country']);

  return errors;
}

