// This file was auto-generated by x10. Do not modify by hand.
// @flow


import { v4 as uuid } from 'uuid';

import { addError, type FormError } from 'react_lib/form/FormProvider';
import isBlank from 'react_lib/utils/isBlank';


// Type Definition
export type Currency = {
  +id: string,
  +symbol: string,
  +name: string,
};


// Create Default Function
export function createDefaultCurrency(): Currency {
  return {
    id: uuid(),
    symbol: '',
    name: '',
  };
}


// Validations
export function currencyCalculateErrors(currency: Currency, prefix?: string): $ReadOnlyArray<FormError> {
  const errors = [];

  if (isBlank(currency.symbol))
    addError(errors, prefix, 'Symbol is required', ['symbol']);
  if (isBlank(currency.name))
    addError(errors, prefix, 'Name is required', ['name']);

  return errors;
}

