// This file was auto-generated by x10. Do not modify by hand.
// @flow


import { v4 as uuid } from 'uuid';

import { addError, type FormError } from 'react_lib/form/FormProvider';
import isBlank from 'react_lib/utils/isBlank';


// Type Definition
export type NetsuiteVendor = {
  +id: string,
  +name: string,
};


// Create Default Function
export function createDefaultNetsuiteVendor(): NetsuiteVendor {
  return {
    id: uuid(),
    name: '',
  };
}


// Validations
export function netsuiteVendorCalculateErrors(netsuiteVendor: NetsuiteVendor, prefix?: string): $ReadOnlyArray<FormError> {
  const errors = [];

  if (isBlank(netsuiteVendor.name))
    addError(errors, prefix, 'Name is required', ['name']);

  return errors;
}

