// This file was auto-generated by x10. Do not modify by hand.
// @flow


import { v4 as uuid } from 'uuid';

import { addError, type FormError } from 'react_lib/form/FormProvider';
import isBlank from 'react_lib/utils/isBlank';


// Type Definition
export type VatNumber = {
  +id: string,
  +number: string,
  +countryRegion: ?string,
};


// Create Default Function
export function createDefaultVatNumber(): VatNumber {
  return {
    id: uuid(),
    number: '',
    countryRegion: null,
  };
}


// Validations
export function vatNumberCalculateErrors(vatNumber: VatNumber, prefix?: string): $ReadOnlyArray<FormError> {
  const errors = [];

  if (isBlank(vatNumber.number))
    addError(errors, prefix, 'Number is required', ['number']);
  if (isBlank(vatNumber.countryRegion))
    addError(errors, prefix, 'Country Region is required', ['countryRegion']);

  return errors;
}

