// This file was auto-generated by x10. Do not modify by hand.
// @flow

import * as React from 'react';
import { createFragmentContainer, graphql } from 'react-relay';

import Group from 'latitude/Group';
import HelpTooltip from 'latitude/HelpTooltip';
import Text from 'latitude/Text';

import Button from 'react_lib/latitude_wrappers/Button';

import { type Address } from 'client_page/entities/Address';

import { type AddressDisplay_address } from './__generated__/AddressDisplay_address.graphql';



type Props = {|
  +address: AddressDisplay_address,
|};
function AddressDisplay(props: Props): React.Node {
  const { address } = props;

  return (
    <Group
      flexDirection='column'
    >
      <Text
        children={ address.theAddress }
      />
      <Text
        children={ address.theAddress2 }
      />
      <Text
        children={ address.city }
      />
      <Text
        children={ address.postalCode }
      />
      <Text
        children={ address.country?.name }
      />
      <Button
        label='Verify'
      />
      <Group>
        <Button
          label='Make Location'
        />
        <HelpTooltip
          text='Create a location with this address...'
        />
      </Group>
    </Group>
  );
}

// $FlowExpectedError
export default createFragmentContainer(AddressDisplay, {
  address: graphql`
    fragment AddressDisplay_address on Address {
      id
      city
      country {
        id
        name
      }
      postalCode
      theAddress
      theAddress2
    }
  `,
});

