// This file was auto-generated by x10. Do not modify by hand.
// @flow

import * as React from 'react';
import { createFragmentContainer, graphql } from 'react-relay';

import Group from 'latitude/Group';
import HelpTooltip from 'latitude/HelpTooltip';
import Text from 'latitude/Text';

import EnumDisplay from 'react_lib/display/EnumDisplay';
import FloatDisplay from 'react_lib/display/FloatDisplay';
import TextDisplay from 'react_lib/display/TextDisplay';
import Button from 'react_lib/latitude_wrappers/Button';
import Table from 'react_lib/table/Table';
import isBlank from 'react_lib/utils/isBlank';
import VisibilityControl from 'react_lib/VisibilityControl';

import { addressSecondAddressLine } from 'small/entities/Address';
import { buildingAgeInYears, PetPolicyEnumPairs, type Building } from 'small/entities/Building';

import { type Buildings_buildings } from './__generated__/Buildings_buildings.graphql';



type Props = {|
  +buildings: Buildings_buildings,
|};
function Buildings(props: Props): React.Node {
  const { buildings } = props;

  return (
    <Group
      flexDirection='column'
    >
      <Text
        scale='display'
        children='Buildings'
      />
      <Table
        data={ buildings }
        columns={
          [
            {
              id: 'Name',
              accessor: (data) => data,
              Cell: ({ value }) =>
                <Group>
                  <TextDisplay
                    value={ value?.name }
                  />
                  <VisibilityControl
                    visible={ !isBlank(value?.description) }
                  >
                    <HelpTooltip
                      text={ value?.description }
                    />
                  </VisibilityControl>
                </Group>
              ,
              Header: 'Name',
              width: 200,
            },
            {
              id: 'The Address',
              accessor: (data) => data?.physicalAddress?.theAddress,
              Cell: ({ value }) =>
                <TextDisplay
                  value={ value }
                />
              ,
              Header: 'The Address',
              width: 140,
            },
            {
              id: 'City / Province',
              accessor: (data) => addressSecondAddressLine(data?.physicalAddress),
              Cell: ({ value }) =>
                <TextDisplay
                  value={ value }
                />
              ,
              Header: 'City / Province',
              width: 140,
            },
            {
              id: 'Age In Years',
              accessor: (data) => buildingAgeInYears(data),
              Cell: ({ value }) =>
                <FloatDisplay
                  value={ value }
                />
              ,
              Header: 'Age In Years',
              width: 140,
            },
            {
              id: 'Pet Policy',
              accessor: (data) => data?.petPolicy,
              Cell: ({ value }) =>
                <EnumDisplay
                  value={ value }
                  options={ PetPolicyEnumPairs }
                />
              ,
              Header: 'Pet Policy',
              width: 140,
            },
            {
              id: 'Action',
              accessor: (data) => data,
              Cell: ({ value }) =>
                <Group>
                  <Button
                    label='View'
                  />
                  <Button
                    label='Edit'
                    url={ '/buildings/edit/' + value?.id }
                  />
                </Group>
              ,
              Header: 'Action',
              width: 140,
            },
          ]
        }
      />
    </Group>
  );
}

// $FlowExpectedError
export default createFragmentContainer(Buildings, {
  buildings: graphql`
    fragment Buildings_buildings on Building @relay(plural: true) {
      id
      dateOfOccupancy
      description
      name
      petPolicy
      physicalAddress {
        id
        city
        stateOrProvince
        theAddress
      }
    }
  `,
});

