// This file was auto-generated by x10. Do not modify by hand.
// @flow

import * as React from 'react';
import { graphql, QueryRenderer } from 'react-relay';

import MultiEntityQueryRenderer from 'react_lib/relay/MultiEntityQueryRenderer';

import environment from 'environment';
import Buildings from 'small/ui/Buildings';



export default function BuildingsInterface(props: { }): React.Node { 
  return (
    <MultiEntityQueryRenderer
      createComponentFunc={ (buildings) => <Buildings buildings={ buildings }/> }
      query={ query }
    />
  );
}

const query = graphql`
  query BuildingsInterfaceQuery {
    entities: buildings {
      ...Buildings_buildings
    }
  }
`;

