// This file was auto-generated by x10. Do not modify by hand.
// @flow

import * as React from 'react';
import { graphql, QueryRenderer } from 'react-relay';

import EntityQueryRenderer from 'react_lib/relay/EntityQueryRenderer';

import environment from 'environment';
import { createDefaultTenant } from 'small/entities/Tenant';
import TenantForm, { TenantFormStateful } from 'small/ui/TenantForm';



type Props = { 
  +id?: string,      // When invoked from another Component
  +match?: {         // When invoked via Route
    +params: { 
      +id: string
    }
  }
};
export default function TenantFormInterface(props: Props): React.Node {
  return (
    <EntityQueryRenderer
      id={ props.id }
      match={ props.match }
      createComponentFunc={ (tenant) => <TenantForm tenant={ tenant }/> }
      createComponentFuncNew={ () => <TenantFormStateful tenant={ createDefaultTenant() }/> }
      query={ query }
    />
  );
}

const query = graphql`
  query TenantFormInterfaceQuery($id: String!) {
    entity: tenant(id: $id) {
      ...TenantForm_tenant
    }
  }
`;

