name: Settings
inheritsFrom: Base
description: Settings for the DPS application. This is a singleton.
datagen_quantity: 1

attributes:
# High Urgency
  - name: highUrgencyShipments
    dataType: Integer
    datagen_min: 5
    datagen_max: 5
  - name: highUrgencyQuotes
    dataType: Integer
    datagen_min: 5
    datagen_max: 5
  - name: highUrgencyBookings
    dataType: Integer
    datagen_min: 5
    datagen_max: 5
  - name: highUrgencyDaysBeforeShipment
    dataType: Integer
    datagen_min: 2
    datagen_max: 2
  - name: highUrgencyEscalated
    dataType: Boolean

# Medium (Middle) Urgency
  - name: mediumUrgencyShipments
    dataType: Integer
    datagen_min: 4
    datagen_max: 4
  - name: mediumUrgencyQuotes
    dataType: Integer
    datagen_min: 4
    datagen_max: 4
  - name: mediumUrgencyBookings
    dataType: Integer
    datagen_min: 4
    datagen_max: 4
  - name: mediumUrgencyDaysBeforeShipment
    dataType: Integer
    datagen_min: 3
    datagen_max: 3

# Automated internal messages
  - name: messageHitDetected
    dataType: String
    default: This shipment, quote or booking is blocked due to possible denied party matches. Non-messaging functions are disabled pending Compliance review.   
    mandatory: true
    ui: TextArea
    label: Hit detected
  - name: messageHitCleared
    dataType: String
    default: The denied party hit has been cleared by Compliance team. This shipment, quote or booking is unblocked.
    mandatory: true
    ui: TextArea
    label: Hit cleared

# Whitelisting - atomic
  - name: defaultWhitelistDurationDays
    dataType: Integer
    mandatory: true
    datagen_probability: 0.0

associations:
# Whitelisting - association
  - name: whitelistDurations
    dataType: WhitelistDuration
    owns: true
    many: true
    datagen_quantity: 4  

# Auto Assignment
  - name: autoAssignments
    dataType: SettingsAutoAssignment
    owns: true
    many: true
    datagen_quantity: 4  

validations:
  - message: High urgency shipments must be greater than medium
    trigger: =highUrgencyShipments <= mediumUrgencyShipments
  - message: High urgency quotes must be greater than medium
    trigger: =highUrgencyQuotes <= mediumUrgencyQuotes
  - message: High urgency bookings must be greater than medium
    trigger: =highUrgencyBookings <= mediumUrgencyBookings
  - message: High urgency days before shipment must be less than medium
    trigger: =highUrgencyDaysBeforeShipment >= mediumUrgencyDaysBeforeShipment
  - message: Whitelist days must be unique
    trigger: =HasDuplicates(whitelistDurations, "value")
  - message: Whitelist day labels must be unique
    trigger: =HasDuplicates(whitelistDurations, "label")
