// This file was auto-generated by x10. Do not modify by hand.
// @flow

import * as React from 'react';
import { createFragmentContainer, graphql } from 'react-relay';

import Checkbox from 'latitude/Checkbox';
import FloatInput from 'latitude/FloatInput';
import Group from 'latitude/Group';
import SelectInput from 'latitude/select/SelectInput';
import Text from 'latitude/Text';
import TextareaInput from 'latitude/TextareaInput';

import FloatDisplay from 'react_lib/display/FloatDisplay';
import TextDisplay from 'react_lib/display/TextDisplay';
import RadioGroup from 'react_lib/enum/RadioGroup';
import FormField from 'react_lib/form/FormField';
import FormProvider from 'react_lib/form/FormProvider';
import FormSection from 'react_lib/form/FormSection';
import FormSubmitButton from 'react_lib/form/FormSubmitButton';
import CalendarDateInput from 'react_lib/latitude_wrappers/CalendarDateInput';
import TextInput from 'react_lib/latitude_wrappers/TextInput';
import VerticalStackPanel from 'react_lib/layout/VerticalStackPanel';
import MultiStacker from 'react_lib/multi/MultiStacker';
import Separator from 'react_lib/Separator';
import StyleControl from 'react_lib/StyleControl';
import toGraphqlEnum from 'react_lib/utils/toGraphqlEnum';
import x10toString from 'react_lib/utils/x10toString';

import { addressSecondAddressLine, createDefaultAddress } from 'small/entities/Address';
import { buildingAgeInYears, buildingApplicableWhenForMailingAddress, buildingCalculateErrors, MailboxTypeEnumPairs, PetPolicyEnumPairs, type Building } from 'small/entities/Building';
import { createDefaultUnit, NumberOfBathroomsEnumPairs } from 'small/entities/Unit';



type Props = {|
  +building: Building,
  +onChange: (building: Building) => void,
|};
function BuildingForm(props: Props): React.Node {
  const { building, onChange } = props;

  return (
    <FormProvider
      value={ { errors: buildingCalculateErrors(building) } }
    >
      <VerticalStackPanel>
        <Text
          scale='display'
          weight='bold'
          children={ 'Editing Building in: ' + x10toString(addressSecondAddressLine(building?.physicalAddress)) }
        />
        <Text
          scale='display'
          weight='bold'
          children={ 'Age in Years: ' + x10toString(buildingAgeInYears(building)) }
        />
        <Separator/>
        <FormSection
          label='Building Info'
        >
          <FormField
            editorFor='moniker'
            label='Moniker'
          >
            <TextDisplay
              value={ building?.moniker }
            />
          </FormField>
          <StyleControl
            maxWidth={ 350 }
          >
            <FormField
              editorFor='name'
              indicateRequired={ true }
              toolTip='A short and memorable name of the Building'
              label='Name'
            >
              <TextInput
                value={ building?.name }
                onChange={ (value) => {
                  // $FlowExpectedError
                  onChange({ ...building, name: value })
                } }
              />
            </FormField>
          </StyleControl>
          <FormField
            editorFor='description'
            toolTip='Description for advertising purposes'
            label='Description'
          >
            <TextareaInput
              value={ building?.description }
              onChange={ (value) => {
                // $FlowExpectedError
                onChange({ ...building, description: value })
              } }
              rows={ 3 }
            />
          </FormField>
        </FormSection>
        <FormSection
          label='Physical Address'
        >
          <FormField
            editorFor='physicalAddress.theAddress'
            indicateRequired={ true }
            label='The Address'
          >
            <TextInput
              value={ building?.physicalAddress?.theAddress }
              onChange={ (value) => {
                let newObj = JSON.parse(JSON.stringify(building));
                newObj.building.physicalAddress.theAddress = value;
                onChange(newObj);
              } }
            />
          </FormField>
          <StyleControl
            maxWidth={ 400 }
          >
            <FormField
              editorFor='physicalAddress.city'
              indicateRequired={ true }
              label='City'
            >
              <TextInput
                value={ building?.physicalAddress?.city }
                onChange={ (value) => {
                  let newObj = JSON.parse(JSON.stringify(building));
                  newObj.building.physicalAddress.city = value;
                  onChange(newObj);
                } }
              />
            </FormField>
          </StyleControl>
          <StyleControl
            maxWidth={ 250 }
          >
            <FormField
              editorFor='physicalAddress.stateOrProvince'
              indicateRequired={ true }
              label='State Or Province'
            >
              <TextInput
                value={ building?.physicalAddress?.stateOrProvince }
                onChange={ (value) => {
                  let newObj = JSON.parse(JSON.stringify(building));
                  newObj.building.physicalAddress.stateOrProvince = value;
                  onChange(newObj);
                } }
              />
            </FormField>
          </StyleControl>
          <StyleControl
            maxWidth={ 150 }
          >
            <FormField
              editorFor='physicalAddress.zip'
              indicateRequired={ true }
              label='Zip or Postal Code'
            >
              <TextInput
                value={ building?.physicalAddress?.zip }
                onChange={ (value) => {
                  let newObj = JSON.parse(JSON.stringify(building));
                  newObj.building.physicalAddress.zip = value;
                  onChange(newObj);
                } }
              />
            </FormField>
          </StyleControl>
        </FormSection>
        <FormSection
          label='Mailing Address'
        >
          <Checkbox
            checked={ building?.mailingAddressSameAsPhysical }
            onChange={ (value) => {
              // $FlowExpectedError
              onChange({ ...building, mailingAddressSameAsPhysical: value })
            } }
            label='Mailing Address Same as Physical Address'
          />
          <StyleControl
            visible={ buildingApplicableWhenForMailingAddress(building) }
          >
            <VerticalStackPanel>
              <FormField
                editorFor='mailingAddress.theAddress'
                indicateRequired={ true }
                label='Address or Post Office (PO) Box'
              >
                <TextInput
                  value={ building?.mailingAddress?.theAddress }
                  onChange={ (value) => {
                    let newObj = JSON.parse(JSON.stringify(building));
                    newObj.building.mailingAddress.theAddress = value;
                    onChange(newObj);
                  } }
                />
              </FormField>
              <StyleControl
                maxWidth={ 400 }
              >
                <FormField
                  editorFor='mailingAddress.city'
                  indicateRequired={ true }
                  label='City'
                >
                  <TextInput
                    value={ building?.mailingAddress?.city }
                    onChange={ (value) => {
                      let newObj = JSON.parse(JSON.stringify(building));
                      newObj.building.mailingAddress.city = value;
                      onChange(newObj);
                    } }
                  />
                </FormField>
              </StyleControl>
              <StyleControl
                maxWidth={ 250 }
              >
                <FormField
                  editorFor='mailingAddress.stateOrProvince'
                  indicateRequired={ true }
                  label='State Or Province'
                >
                  <TextInput
                    value={ building?.mailingAddress?.stateOrProvince }
                    onChange={ (value) => {
                      let newObj = JSON.parse(JSON.stringify(building));
                      newObj.building.mailingAddress.stateOrProvince = value;
                      onChange(newObj);
                    } }
                  />
                </FormField>
              </StyleControl>
              <StyleControl
                maxWidth={ 150 }
              >
                <FormField
                  editorFor='mailingAddress.zip'
                  indicateRequired={ true }
                  label='Zip or Postal Code'
                >
                  <TextInput
                    value={ building?.mailingAddress?.zip }
                    onChange={ (value) => {
                      let newObj = JSON.parse(JSON.stringify(building));
                      newObj.building.mailingAddress.zip = value;
                      onChange(newObj);
                    } }
                  />
                </FormField>
              </StyleControl>
            </VerticalStackPanel>
          </StyleControl>
        </FormSection>
        <FormSection
          label='Other Details'
        >
          <Group
            gap={ 40 }
          >
            <FormField
              editorFor='dateOfOccupancy'
              indicateRequired={ true }
              label='Date Of Occupancy'
            >
              <CalendarDateInput
                value={ building?.dateOfOccupancy }
                onChange={ (value) => {
                  // $FlowExpectedError
                  onChange({ ...building, dateOfOccupancy: value })
                } }
              />
            </FormField>
            <FormField
              editorFor='ageInYears'
              toolTip='Strongly affects annual propery maintenance costs.'
              label='Age In Years'
            >
              <FloatDisplay
                value={ buildingAgeInYears(building) }
              />
            </FormField>
          </Group>
          <FormField
            editorFor='mailboxType'
            indicateRequired={ true }
            label='Mailbox Type'
          >
            <RadioGroup
              value={ building?.mailboxType }
              onChange={ (value) => {
                // $FlowExpectedError
                onChange({ ...building, mailboxType: value })
              } }
              options={ MailboxTypeEnumPairs }
            />
          </FormField>
          <FormField
            editorFor='petPolicy'
            label='Pet Policy'
          >
            <SelectInput
              value={ building?.petPolicy }
              onChange={ (value) => {
                // $FlowExpectedError
                onChange({ ...building, petPolicy: value })
              } }
              options={ PetPolicyEnumPairs }
            />
          </FormField>
        </FormSection>
        <FormSection
          label='Units'
        >
          <MultiStacker
            items={ building?.units }
            onChange={ (value) => {
              // $FlowExpectedError
              onChange({ ...building, units: value })
            } }
            itemDisplayFunc={ (data, onChange) => (
              <VerticalStackPanel>
                <Group
                  alignItems='center'
                >
                  <FormField
                    editorFor='number'
                    indicateRequired={ true }
                    toolTip='Unit number corresponding to mailing address'
                    label='Number'
                  >
                    <TextInput
                      value={ data?.number }
                      onChange={ (value) => {
                        // $FlowExpectedError
                        onChange({ ...data, number: value })
                      } }
                    />
                  </FormField>
                  <FormField
                    editorFor='squareFeet'
                    label='Square Feet'
                  >
                    <FloatInput
                      value={ data?.squareFeet }
                      onChange={ (value) => {
                        // $FlowExpectedError
                        onChange({ ...data, squareFeet: value })
                      } }
                      decimalPrecision={ 0 }
                    />
                  </FormField>
                  <FormField
                    editorFor='hasBalcony'
                    indicateRequired={ true }
                    label='Unit has Blacony?'
                  >
                    <Checkbox
                      checked={ data?.hasBalcony }
                      onChange={ (value) => {
                        // $FlowExpectedError
                        onChange({ ...data, hasBalcony: value })
                      } }
                    />
                  </FormField>
                </Group>
                <Group
                  alignItems='center'
                >
                  <FormField
                    editorFor='numberOfBedrooms'
                    indicateRequired={ true }
                    label='Number Of Bedrooms'
                  >
                    <FloatInput
                      value={ data?.numberOfBedrooms }
                      onChange={ (value) => {
                        // $FlowExpectedError
                        onChange({ ...data, numberOfBedrooms: value })
                      } }
                    />
                  </FormField>
                  <FormField
                    editorFor='numberOfBathrooms'
                    indicateRequired={ true }
                    label='Number Of Bathrooms'
                  >
                    <SelectInput
                      value={ data?.numberOfBathrooms }
                      onChange={ (value) => {
                        // $FlowExpectedError
                        onChange({ ...data, numberOfBathrooms: value })
                      } }
                      options={ NumberOfBathroomsEnumPairs }
                    />
                  </FormField>
                </Group>
              </VerticalStackPanel>
            ) }
            addItemLabel='Add Unit'
            addNewItem={ createDefaultUnit }
          />
        </FormSection>
        <Group
          justifyContent='space-between'
        >
          <TextDisplay
            value='* Required'
          />
          <FormSubmitButton
            mutation={ mutation }
            variables={
              {
                building: {
                  id: building.id,
                  physicalAddress: building.physicalAddress,
                  dateOfOccupancy: building.dateOfOccupancy,
                  moniker: building.moniker,
                  name: building.name,
                  description: building.description,
                  mailingAddressSameAsPhysical: building.mailingAddressSameAsPhysical,
                  mailingAddress: building.mailingAddress,
                  mailboxType: toGraphqlEnum(building.mailboxType),
                  petPolicy: toGraphqlEnum(building.petPolicy),
                  units: building.units,
                }
              }
            }
            label='Save'
          />
        </Group>
      </VerticalStackPanel>
    </FormProvider>
  );
}

type StatefulProps = {|
  +building: Building,
|};
export function BuildingFormStateful(props: StatefulProps): React.Node {
  const building = relayToInternal(props.building);
  const [editedBuilding, setEditedBuilding] = React.useState(building);
  return <BuildingForm
    building={ editedBuilding }
    onChange={ setEditedBuilding }
  />
}

function relayToInternal(relay: any): Building {
  return {
    ...relay,
    mailingAddress: relay.mailingAddress || createDefaultAddress(),
  };
}

const mutation = graphql`
  mutation BuildingFormMutation(
    $building: BuildingFormBuildingInput!
  ) {
    buildingFormUpdateBuilding(
      data: $building
    ) {
      id
      dateOfOccupancy
      description
      mailboxType
      mailingAddress {
        id
        city
        stateOrProvince
        theAddress
        zip
      }
      mailingAddressSameAsPhysical
      moniker
      name
      petPolicy
      physicalAddress {
        id
        city
        stateOrProvince
        theAddress
        zip
      }
      units {
        id
        hasBalcony
        number
        numberOfBathrooms
        numberOfBedrooms
        squareFeet
      }
    }
  }
`;

// $FlowExpectedError
export default createFragmentContainer(BuildingFormStateful, {
  building: graphql`
    fragment BuildingForm_building on Building {
      id
      dateOfOccupancy
      description
      mailboxType
      mailingAddress {
        id
        city
        stateOrProvince
        theAddress
        zip
      }
      mailingAddressSameAsPhysical
      moniker
      name
      petPolicy
      physicalAddress {
        id
        city
        stateOrProvince
        theAddress
        zip
      }
      units {
        id
        hasBalcony
        number
        numberOfBathrooms
        numberOfBedrooms
        squareFeet
      }
    }
  `,
});

