name: ProductHsCode
description: >
  An assignment of a <Product> to an <HsCode> within the scope of a particular country

attributes:
  - countryCode:
      dataType: string
  - verifiedByBroker:
      dataType: boolean
  - archived:
      dataType: boolean

associations:
  - belongsTo: HsCode
  - belongsTo: Product
