name: Product
description: >
  A type of physical product that can be associated with a <PurchaseOrderItem>

attributes:
  - name: productName
    dataType: String
  - name: sku
    description: "'Stock Keeping Unit' -- a unique product id within the <Company>"
    dataType: String

associations:
  - name: company
    dataType: Company