name: ProductHsCode
description: >
  An assignment of a <Product> to an <HsCode> within the scope of a particular country

attributes:
  - name: countryCode
    dataType: String
  - name: verifiedByBroker
    dataType: Boolean
  - name: archived
    dataType: Boolean

associations:
  - name: hsCode
    dataType: HsCode
  - name: product
    dataType: Product
